### ISSUE TITLE
reactive relations

### ISSUE THREAD

**Issue by omnidan** [Goluis/cottz-publish#7]
My current code is:

``` javascript
  Publish.relations(this, Posts.find({}, {sort: {points: -1}}), function (id, doc) {
    doc.user = this.cursor(Meteor.users.find(doc.user))
      .changeParentDoc(function (userId, user) {
        return user;
      });
  });
```

When the points of a user change, my React components are not re-rendering as the data change is within the relation - if I change, e.g. the post title, it updates it fine.

Are reactive relations like this possible with this module? If yes, how would I do it?

**Comment by lfades** [comment]
Omnidan Hello, thank you very much for using my package

I have 2 recommendations to give

1- Use this package https://github.com/Goluis/cottz-publish-relations, I stop supporting this by its internal code and other problems
2- When I created ChangeParentDoc not consider performance issues,
I really recommend you use much more .publish () to send users to the collection of the users and does not modify the Post

**Comment by omnidan** [comment]
@Goluis Thanks for your response. I don't think 2 is an option for me, as I need some user data in the post. How would I use your `cottz-publish-relations` package to achieve that?

Thanks in advance.

**Comment by lfades** [comment]
with publish-relations using the 2 option

``` js
this.cursor(Posts.find({}, {sort: {points: -1}}), function (id, doc) {
    if (doc.user) {
        this.cursor(Meteor.users.find(doc.user));
    }
});
```

in the template you can create a helper to bring the user. If the user can not publish in Meteor.users the second parameter is any other collection, for example:

``` js
this.cursor(Meteor.users.find(doc.user)); // <-- collection: Meteor.users
this.cursor(Meteor.users.find(doc.user), 'postsUsers');

// client
var users = new Mongo.Collection('postsUsers');
```

with publish-relations using the 1 option

I have some knowledge about why the second option is a good idea, Meteor lost some performance when upgrading sub-documents, but if you need so this is the best solution

``` js
var self = this;
this.cursor(Posts.find({}, {sort: {points: -1}}), function (id, doc) {
    if (doc.user) {
        this.observeChanges(Meteor.users.find(doc.user), {
            added: function (userId, user) {
                doc.user = user;
            },
            changed: function (userId, user) {
                // We add the changes to the user got in added and send it
                self.changed('posts', id, {user: _.extend(doc.user, user)});
            }
        });
    }
});
```

I don't use ChangeParentDoc because all changes will go to post and not to the user.
It is not a simple solution maybe because I had not found the need to implement, if you can give me more information about why this is the best method I would appreciate, maybe you can improve the package ^^

**Comment by omnidan** [comment]
@Goluis thanks a lot for all the examples - it all makes more sense now. I decided to go a different route and request the user information in the template. (as you have suggested too)
